const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
    /**
     * User Insight Model (The Prism).
     * 
     * Stores deep psychological insights generated by AI based on user activity.
     * Acts as a "mirror" for the user to understand themselves better.
     * 
     * @typedef {Object} UserInsight
     * @property {string} id - Unique UUID
     * @property {string} userId - User UUID
     * @property {string} type - 'personality' | 'habit' | 'suggestion' | 'prediction'
     * @property {string} content - The insight text
     * @property {number} confidence - AI confidence score (0-1)
     * @property {Object} metadata - Additional data (e.g., related posts)
     * @property {Date} createdAt
     */
    const UserInsight = sequelize.define('UserInsight', {
        id: {
            type: DataTypes.UUID,
            defaultValue: DataTypes.UUIDV4,
            primaryKey: true
        },
        userId: {
            type: DataTypes.UUID,
            allowNull: false,
            references: {
                model: 'users',
                key: 'id'
            },
            onDelete: 'CASCADE'
        },
        type: {
            type: DataTypes.ENUM('personality', 'habit', 'suggestion', 'prediction'),
            allowNull: false,
            comment: 'Category of the insight'
        },
        content: {
            type: DataTypes.TEXT,
            allowNull: false,
            comment: 'The actual insight text displayed to the user'
        },
        confidence: {
            type: DataTypes.FLOAT,
            allowNull: true,
            defaultValue: 0.8,
            validate: { min: 0, max: 1 }
        },
        metadata: {
            type: DataTypes.JSON,
            allowNull: true,
            comment: 'Source data or context for the insight'
        }
    }, {
        tableName: 'user_insights',
        timestamps: true,
        indexes: [
            {
                fields: ['userId', 'type']
            },
            {
                fields: ['createdAt']
            }
        ]
    });

    UserInsight.associate = (models) => {
        UserInsight.belongsTo(models.User, {
            foreignKey: 'userId',
            as: 'user'
        });
    };

    return UserInsight;
};

